version: "3.7"

services:
  adonis_app:
    container_name: adonis_app
    networks:
      - adonis_network
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 5173:5173
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: dumb-init npm run dev --host

networks:
  adonis_network:
    driver: bridge
